package m.delegatii.enums;

public enum TipAnjagat {
	AV, SD, DV, ATR, DAG, DFL, DINV, DPR, DHR, DTR, DZ, DD, DRU, DZBUC, SBDEZ, DA, DADMIN, CAG, SM, SSDTI, SSISCIR, SSMEC, CJ, SSIT, SSJ, SSLO, SSSSMSU, KA, ARC, GD, IOFR08, IHR, ISSM, MAC, MM, MMPROD, OIVPD, OC, RGEST, SBA, SDCVA, SDKA, SSFC, SSPROD, SOF, SHR, STIV, DPROD, CFP, DENDET, DE, DEA, DFIN, DG, DIT, DJ, DMK, DP, ISI, MP, SSCFC, MSPEC, RMK, SBCFI, SBIT, SBMK, SSAI, SSCFI, SSC, TO, ICL, DAP, GS, CONS_GED, SSIC, DDEZ

}
